workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    scripts:
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
