name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Show Gradle version and environment info
        run: |
          ./gradlew --version
          env

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Download Android SDK tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/Android/Sdk/cmdline-tools
          mkdir -p $HOME/Android/Sdk/cmdline-tools/latest
          mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools/* $HOME/Android/Sdk/cmdline-tools/latest/
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android/Sdk "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      - name: Build APK (verbose)
        env:
          ANDROID_SDK_ROOT: ${{ runner.home }}/Android/Sdk
        run: ./gradlew assembleDebug --info

      - name: List all files in project root
        run: ls -R

      - name: List build output folders
        run: |
          ls -R app/build || echo "No app/build folder"
          ls -R */build || echo "No other build folders"

      - name: Upload APK artifact (all APKs)
        uses: actions/upload-artifact@v4
        with:
          name: TSI-Sports_C-debug.apk
          path: '**/*.apk'
